// ============================================================
//  ÉPISODES — CONTENU
//  Chaque projet est un épisode : un numéro, un titre,
//  un synopsis et un générique de production.
//  👉 Tout se modifie ici.
// ============================================================

const PERSONNAGE = {
  nom: "AYOUB OUAADOUD",
  kana: "アユーブ",
  classe: "DÉVELOPPEUR",
  base: "Bruxelles, Belgique",
  ecole: "Erasmushogeschool Brussel",
  github: "https://github.com/AyoubO22",
  linkedin: "https://www.linkedin.com/in/ayoub-ouaadoud-5a9550293",
  email: "ayoub.ouaadoud@student.ehb.be",
  citation: "Finir, mettre en ligne, montrer. Le reste attend son tour.",
  capacites: [
    ["JS / TYPESCRIPT", 85], ["REACT / TAILWIND", 80], ["SWIFT / SWIFTUI", 75],
    ["GIT / CI-CD", 75], ["NODE.JS / API", 70], ["PYTHON", 65],
    ["SQL / DONNÉES", 60], ["C# / .NET", 60], ["JAVA / SPRING", 55], ["PHP / LARAVEL", 55],
  ],
};

/* --- vignette : 0 à 3 (composition) · duo : 0 à 5 (couleurs) --- */
const EPISODES = [
  {
    n: "01",
    id: "gameboxd",
    titre: "LE REGISTRE",
    sous: "Gameboxd",
    genre: "APPLICATION iOS",
    annee: "2026",
    vignette: 0, duo: 0,
    synopsis: "Noter, critiquer, garder trace de chaque partie jouée. Une application iOS native qui traite le jeu vidéo comme on traite les films : avec des archives tenues à jour.",
    staff: [
      ["制作", "Swift 5 · SwiftUI"],
      ["構成", "Architecture MVVM — 52 fichiers"],
      ["資料", "API RAWG"],
      ["特別", "Extension widget WidgetKit"],
      ["品質", "Tests unitaires · GitHub Actions"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Gameboxd" }],
  },
  {
    n: "02",
    id: "pokedex",
    titre: "LA MÉTHODE",
    sous: "Encyclopédie compétitive",
    genre: "PLATEFORME WEB",
    annee: "2026",
    vignette: 1, duo: 1,
    synopsis: "Mille vingt-cinq créatures, neuf cents attaques, quinze sections de stratégie écrites à la main. Un guide qui n'énumère pas : il explique pourquoi une équipe tient debout.",
    staff: [
      ["制作", "React 18 · TypeScript · Vite"],
      ["構成", "61 composants · Tailwind · Radix"],
      ["資料", "PokéAPI — 1025 fiches"],
      ["特別", "Calculateur de dégâts · constructeur d'équipe"],
      ["品質", "Import Showdown · quiz de 74 questions"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Pokemon-guide" }],
  },
  {
    n: "03",
    id: "crm",
    titre: "LE PASSAGE",
    sous: "Service d'intégration CRM",
    genre: "BACK-END · ÉQUIPE",
    annee: "2026",
    vignette: 2, duo: 2,
    synopsis: "Entre une file de messages et un CRM, cinq autres services attendent leur tour. Rien ne doit se perdre en route, et tout ce qui échoue doit pouvoir être rejoué.",
    staff: [
      ["制作", "Node.js · RabbitMQ"],
      ["構成", "Validation XSD — 49 schémas"],
      ["資料", "Salesforce · jsforce"],
      ["特別", "Files de reprise et file morte"],
      ["品質", "Docker · Compose · CI · projet d'équipe"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/IntegrationProject-Groep1/CRM" }],
  },
  {
    n: "04",
    id: "corplol",
    titre: "À ARMES ÉGALES",
    sous: "Corplol",
    genre: "APPLICATION DE BUREAU",
    annee: "2026",
    vignette: 3, duo: 3,
    synopsis: "Cinq joueurs de force inégale, et deux équipes à former sans que le résultat soit joué d'avance. Le calcul s'en charge, Discord reçoit la composition.",
    staff: [
      ["制作", "Python 3.11 · CustomTkinter"],
      ["構成", "Roster · disponibilités · historique"],
      ["資料", "API Riot Games"],
      ["特別", "Équilibrage 5v5 par score et par rôle"],
      ["品質", "discord.py · licence MIT"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/corplol" }],
  },
  {
    n: "05",
    id: "eylen",
    titre: "L'ADRESSE",
    sous: "Eylen Kliniek",
    genre: "SITE CLIENT · EN LIGNE",
    annee: "2026",
    vignette: 0, duo: 4,
    synopsis: "Un cabinet médical, un vrai commanditaire, un vrai public. Pas de framework, pas d'effets : une page qui se charge et se lit, au téléphone d'abord.",
    staff: [
      ["制作", "HTML · CSS · JavaScript"],
      ["構成", "Page unique, sans dépendance"],
      ["特別", "Déploiement automatique à chaque poussée"],
      ["品質", "En ligne"],
    ],
    liens: [
      { label: "VOIR LE SITE", url: "https://zohra-fellah.github.io/Eylen-Kliniek/" },
      { label: "CODE SOURCE", url: "https://github.com/Zohra-Fellah/Eylen-Kliniek" },
    ],
  },
  {
    n: "06",
    id: "sanzo",
    titre: "CENT CINQUANTE-NEUF TEINTES",
    sous: "Sanzo Outfit Matcher",
    genre: "APPLICATION macOS",
    annee: "2026",
    vignette: 1, duo: 5,
    synopsis: "Un peintre japonais a relevé cent cinquante-neuf couleurs dans les années trente, et trois cent quarante-huit façons de les associer. L'application se contente de lui poser la question.",
    staff: [
      ["制作", "Swift · SwiftUI · macOS"],
      ["資料", "Nuancier de Sanzo Wada"],
      ["特別", "348 palettes harmonieuses"],
      ["品質", "Licence MIT"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/SanzoOutfitMatcher" }],
  },
  {
    n: "07",
    id: "recrutement",
    titre: "TROIS REGARDS",
    sous: "Plateforme de recrutement",
    genre: "PLATEFORME WEB",
    annee: "2026",
    vignette: 2, duo: 1,
    synopsis: "Celui qui recrute, celui qui décide, et celui qui attend une réponse. Le troisième est trop souvent oublié : ici, il voit exactement où en est son dossier.",
    staff: [
      ["制作", "React · TypeScript · Vite"],
      ["構成", "72 composants · Tailwind · Radix"],
      ["特別", "Évaluation structurée, non libre"],
      ["品質", "Tableaux de bord Recharts"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/HR-App" }],
  },
  {
    n: "08",
    id: "undercover",
    titre: "L'INFILTRÉ",
    sous: "Undercover",
    genre: "JEU WEB · EN LIGNE",
    annee: "2026",
    vignette: 3, duo: 0,
    synopsis: "Tous reçoivent le même mot. Sauf un, qui en reçoit un autre. Et un dernier, qui n'a rien reçu du tout et devra faire semblant jusqu'à la fin.",
    staff: [
      ["制作", "HTML · CSS · JavaScript"],
      ["構成", "Trois fichiers, aucune dépendance"],
      ["特別", "Un seul téléphone qui circule"],
      ["品質", "En ligne"],
    ],
    liens: [
      { label: "JOUER", url: "https://ayoubo22.github.io/undercover/" },
      { label: "CODE SOURCE", url: "https://github.com/AyoubO22/undercover" },
    ],
  },
  {
    n: "09",
    id: "crema",
    titre: "PAS DE SECONDE SOIRÉE",
    sous: "Invitation & RSVP",
    genre: "PAGE ÉVÉNEMENT",
    annee: "2026",
    vignette: 0, duo: 3,
    synopsis: "Une invitation, un formulaire, et l'obligation que ça marche du premier coup. Une réponse perdue est une place vide : tout est construit autour de ça.",
    staff: [
      ["制作", "HTML · CSS · JavaScript"],
      ["資料", "Google Apps Script"],
      ["特別", "Bascule courriel si le service ne répond pas"],
      ["品質", "Page non indexée"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Crema" }],
  },
  {
    n: "10",
    id: "episodes",
    titre: "CET ÉPISODE",
    sous: "Le portfolio que vous lisez",
    genre: "PORTFOLIO",
    annee: "2026",
    vignette: 2, duo: 4,
    synopsis: "Les vignettes, les trames et les traits de vitesse sont composés au code. Aucune image n'est chargée. Ce portfolio existe en quatre versions : celle-ci en est une.",
    staff: [
      ["制作", "HTML · CSS · JavaScript"],
      ["構成", "Vignettes composées depuis une graine"],
      ["特別", "Transition eyecatch entre les épisodes"],
      ["品質", "Aucune librairie"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/undercover/tree/main/portfolio" }],
  },
];

const ANNEES = [
  ["2026", "Gameboxd", "Application iOS en SwiftUI — MVVM, API RAWG, widget, tests, CI."],
  ["2026", "Service d'intégration CRM", "En équipe : RabbitMQ, Salesforce, XSD, Docker."],
  ["2026", "Encyclopédie compétitive", "React, TypeScript, PokéAPI, calculateur et team builder."],
  ["2026", "Eylen Kliniek", "Site d'un cabinet médical, livré et en ligne."],
  ["2026", "Corplol · Sanzo · Plateforme RH · Undercover", "Python, macOS, React, vanilla."],
  ["2025", "Credibill", "Suite .NET — WPF, ASP.NET, MAUI. API Laravel."],
  ["2024", "GamerGalaxy · Anderlechtse Gazette", "Laravel, Spring Boot, Python et Pandas."],
  ["—", "Erasmushogeschool Brussel", "Bruxelles. Français, néerlandais, anglais."],
];
