// ============================================================
//  LA FAILLE — CONTENU
//  Chaque projet est un champion : un titre, des rôles,
//  cinq sorts, et des statistiques.
//  👉 Tout se modifie ici.
// ============================================================

const INVOCATEUR = {
  nom: "AYOUB OUAADOUD",
  titre: "DÉVELOPPEUR",
  lieu: "Bruxelles, Belgique",
  ecole: "Erasmushogeschool Brussel",
  niveau: 26,
  rang: "PLATINE",
  github: "https://github.com/AyoubO22",
  linkedin: "https://www.linkedin.com/in/ayoub-ouaadoud-5a9550293",
  email: "ayoub.ouaadoud@student.ehb.be",
};

/* --- statistiques : technique, portée, finition, difficulté (0 à 10) --- */
const CHAMPIONS = [
  {
    id: "gameboxd",
    nom: "GAMEBOXD",
    titre: "le Chroniqueur",
    roles: ["APPLICATION iOS", "SWIFTUI"],
    graine: 51027,
    annee: "2026",
    stats: [9, 7, 9, 8],
    resume: "Un journal de jeux vidéo : noter, critiquer, garder trace de ce qu'on a joué.",
    sorts: [
      ["P", "ARCHITECTURE MVVM", "Le projet est découpé en Models, Services, ViewModels et Views. Cinquante-deux fichiers Swift qui savent où ils habitent."],
      ["Q", "RECHERCHE RAWG", "Interroge l'API RAWG pour retrouver n'importe quel jeu et remplir sa fiche automatiquement."],
      ["W", "BIBLIOTHÈQUE", "Notes, critiques et statut de lecture, conservés localement sur l'appareil."],
      ["E", "WIDGET", "Extension WidgetKit : la dernière partie consignée s'affiche sur l'écran d'accueil."],
      ["R", "LIVRAISON", "Tests unitaires, intégration continue GitHub Actions, localisation française et anglaise, clés d'API tenues hors du dépôt."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Gameboxd" }],
  },
  {
    id: "pokedex",
    nom: "POKÉDEX COMPÉTITIF",
    titre: "le Stratège",
    roles: ["PLATEFORME WEB", "REACT · TYPESCRIPT"],
    graine: 25025,
    annee: "2026",
    stats: [8, 10, 8, 7],
    resume: "Guide complet du jeu compétitif : mille vingt-cinq fiches, neuf cents attaques, et les outils pour bâtir une équipe.",
    sorts: [
      ["P", "QUINZE SECTIONS", "Le contenu stratégique est écrit, pas généré : types, stats, talents, objets, statuts, mécaniques, teambuilding."],
      ["Q", "POKÉDEX COMPLET", "Connecté à PokéAPI : 1025 créatures, avec analyse compétitive et matchups."],
      ["W", "CALCULATEUR DE DÉGÂTS", "Sélection des deux camps via l'API, calcul en direct."],
      ["E", "CONSTRUCTEUR D'ÉQUIPE", "Analyse en temps réel des faiblesses, de la couverture et des rôles. Importe un paste Pokémon Showdown."],
      ["R", "QUIZ", "Soixante-quatorze questions avec explications, pour vérifier qu'on a retenu."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Pokemon-guide" }],
  },
  {
    id: "crm",
    nom: "SERVICE CRM",
    titre: "le Passeur",
    roles: ["BACK-END", "NODE.JS · RABBITMQ"],
    graine: 8801,
    annee: "2026",
    stats: [10, 9, 8, 10],
    resume: "La couche d'intégration entre une file de messages, Salesforce, et cinq autres services. Projet d'équipe.",
    sorts: [
      ["P", "FILE D'ATTENTE", "Consomme des messages XML sur plusieurs files et échanges RabbitMQ."],
      ["Q", "VALIDATION XSD", "Vérifie la structure de chaque message contre quarante-neuf schémas avant de le laisser passer."],
      ["W", "IDENTITÉ MAÎTRE", "Résout ou crée un identifiant unique auprès du service d'identité."],
      ["E", "SALESFORCE", "Crée et met à jour les enregistrements, puis réémet vers la caisse, la facturation, le mailing et le planning."],
      ["R", "REPRISE", "Files de reprise pour les échecs temporaires, file morte pour le reste. Rien ne disparaît en silence."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/IntegrationProject-Groep1/CRM" }],
  },
  {
    id: "corplol",
    nom: "CORPLOL",
    titre: "le Capitaine",
    roles: ["APPLICATION BUREAU", "PYTHON · API RIOT"],
    graine: 4400,
    annee: "2026",
    stats: [7, 8, 7, 6],
    resume: "Gestionnaire d'équipes League of Legends : un roster, des disponibilités, et deux camps équilibrés générés automatiquement.",
    sorts: [
      ["P", "ROSTER", "Rang, rôles, pseudo et disponibilités hebdomadaires de chaque joueur."],
      ["Q", "ÉQUILIBRAGE 5v5", "Génère deux équipes de force comparable, en respectant les rôles de chacun."],
      ["W", "STATISTIQUES RIOT", "KDA, rang et parties récentes récupérés depuis l'API officielle."],
      ["E", "HISTORIQUE", "Enregistre les matchs, désigne le vainqueur, suit les victoires et les défaites."],
      ["R", "EXPORT DISCORD", "Copie la composition déjà formatée pour être collée dans le salon."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/corplol" }],
  },
  {
    id: "eylen",
    nom: "EYLEN KLINIEK",
    titre: "la Vitrine",
    roles: ["SITE CLIENT", "EN LIGNE"],
    graine: 6031,
    annee: "2026",
    stats: [5, 6, 9, 4],
    resume: "Site d'un cabinet de médecine esthétique et fonctionnelle. Un vrai commanditaire, une vraie mise en ligne.",
    sorts: [
      ["P", "SANS FRAMEWORK", "Une seule page, HTML, CSS et JavaScript. Rien à charger, rien à attendre."],
      ["Q", "LECTURE MOBILE", "Structuré pour être lu au téléphone d'abord, puisque c'est là que les patients le trouvent."],
      ["W", "CONTENU PATIENT", "Services, informations pratiques et prise de contact, dans la langue du public visé."],
      ["E", "DÉPLOIEMENT", "Publication automatique à chaque poussée, via GitHub Actions."],
      ["R", "EN LIGNE", "Le seul travail qui compte vraiment est celui qu'on peut ouvrir."],
    ],
    liens: [
      { label: "VOIR LE SITE", url: "https://zohra-fellah.github.io/Eylen-Kliniek/" },
      { label: "CODE SOURCE", url: "https://github.com/Zohra-Fellah/Eylen-Kliniek" },
    ],
  },
  {
    id: "sanzo",
    nom: "SANZO MATCHER",
    titre: "le Coloriste",
    roles: ["APPLICATION macOS", "SWIFTUI"],
    graine: 15948,
    annee: "2026",
    stats: [7, 6, 8, 6],
    resume: "Application macOS qui propose des tenues coordonnées à partir des palettes du peintre Sanzo Wada.",
    sorts: [
      ["P", "159 TEINTES", "Le nuancier relevé par Sanzo Wada dans les années trente, intégralement numérisé."],
      ["Q", "PIPETTE", "Sélection par pipette, code hexadécimal, ou clic direct dans le nuancier."],
      ["W", "348 PALETTES", "Les combinaisons harmonieuses du peintre servent de moteur de suggestion."],
      ["E", "TENUE COMPLÈTE", "Propositions réparties en haut, bas, veste et accessoire."],
      ["R", "NATIF", "SwiftUI sur macOS : pensé pour le clavier et la souris, pas pour un navigateur déguisé."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/SanzoOutfitMatcher" }],
  },
  {
    id: "recrutement",
    nom: "PLATEFORME RH",
    titre: "le Recruteur",
    roles: ["PLATEFORME WEB", "REACT · TYPESCRIPT"],
    graine: 7212,
    annee: "2026",
    stats: [8, 8, 7, 7],
    resume: "Centralise un processus de recrutement complet, de la demande de poste à la décision finale.",
    sorts: [
      ["P", "TROIS RÔLES", "Recruteur, manager et candidat voient chacun ce qui les concerne."],
      ["Q", "VACANCES", "Le manager demande un poste, le recruteur le publie et trie les candidatures."],
      ["W", "ÉVALUATION", "Grille structurée plutôt qu'appréciation libre : les entretiens se comparent."],
      ["E", "SUIVI CANDIDAT", "Le candidat voit où en est son dossier, ce qui est rare et devrait l'être moins."],
      ["R", "TABLEAUX DE BORD", "Soixante-douze composants, graphiques de suivi, d'après un prototype haute-fidélité."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/HR-App" }],
  },
  {
    id: "undercover",
    nom: "UNDERCOVER",
    titre: "l'Infiltré",
    roles: ["JEU WEB", "EN LIGNE"],
    graine: 1337,
    annee: "2026",
    stats: [5, 5, 8, 3],
    resume: "Jeu de société local : un seul téléphone qui circule, et un mot que tout le monde n'a pas reçu.",
    sorts: [
      ["P", "UN SEUL ÉCRAN", "Le téléphone passe de main en main. Aucun serveur, aucun compte."],
      ["Q", "DISTRIBUTION", "Rôles attribués et équilibrés automatiquement selon le nombre de joueurs."],
      ["W", "DÉBAT", "Chacun décrit son mot sans le prononcer, dans l'ordre affiché."],
      ["E", "VOTE", "Élimination à la majorité, avec révélation du rôle."],
      ["R", "DERNIÈRE CHANCE", "Mr. White éliminé peut encore deviner le mot des civils et renverser la partie."],
    ],
    liens: [
      { label: "JOUER", url: "https://ayoubo22.github.io/undercover/" },
      { label: "CODE SOURCE", url: "https://github.com/AyoubO22/undercover" },
    ],
  },
  {
    id: "crema",
    nom: "INVITATION RSVP",
    titre: "l'Hôte",
    roles: ["PAGE ÉVÉNEMENT", "APPS SCRIPT"],
    graine: 5241,
    annee: "2026",
    stats: [4, 4, 8, 4],
    resume: "Une invitation et son formulaire de réponse. Court, mais il devait marcher du premier coup.",
    sorts: [
      ["P", "PAS DE SECONDE SOIRÉE", "Une réponse perdue est une place vide. Tout est construit autour de ça."],
      ["Q", "FEUILLE DE CALCUL", "Les réponses arrivent dans une feuille Google via Apps Script."],
      ["W", "SECOURS", "Si le script ne répond pas, le formulaire bascule sur l'envoi courriel sans bloquer l'invité."],
      ["E", "MISE EN PAGE", "Soignée, lisible au téléphone, adaptée au ton de l'événement."],
      ["R", "DISCRÉTION", "Page non indexée : c'est une invitation privée, pas une vitrine."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Crema" }],
  },
  {
    id: "faille",
    nom: "CETTE SÉLECTION",
    titre: "le Miroir",
    roles: ["PORTFOLIO", "HTML · CSS · JS"],
    graine: 999,
    annee: "2026",
    stats: [7, 6, 9, 6],
    resume: "L'écran où vous vous trouvez. Un portfolio construit comme une sélection de champions.",
    sorts: [
      ["P", "AUCUNE IMAGE", "Emblèmes, trames et lueurs sont dessinés au code. Rien n'est chargé."],
      ["Q", "EMBLÈMES", "Chaque champion porte un sceau hexagonal généré depuis sa graine."],
      ["W", "SORTS", "Les fonctionnalités de chaque projet sont présentées comme un kit complet."],
      ["E", "SANS LIBRAIRIE", "HTML, CSS et JavaScript purs. Aucune dépendance à installer."],
      ["R", "QUATRE MONDES", "Ce portfolio existe en quatre versions. Celle-ci en est une."],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/undercover/tree/main/portfolio" }],
  },
];

const MAITRISES = [
  ["JS / TYPESCRIPT", 85], ["REACT / TAILWIND", 80], ["SWIFT / SWIFTUI", 75],
  ["GIT / CI-CD", 75], ["NODE.JS / API", 70], ["PYTHON", 65],
  ["SQL / DONNÉES", 60], ["C# / .NET", 60], ["JAVA / SPRING", 55], ["PHP / LARAVEL", 55],
];

const HISTORIQUE = [
  ["V", "2026", "Gameboxd", "Application iOS en SwiftUI — MVVM, API RAWG, widget, tests, CI."],
  ["V", "2026", "Service d'intégration CRM", "En équipe : RabbitMQ, Salesforce, XSD, Docker."],
  ["V", "2026", "Pokédex compétitif", "React, TypeScript, PokéAPI, calculateur et team builder."],
  ["V", "2026", "Eylen Kliniek", "Site d'un cabinet médical, livré et en ligne."],
  ["V", "2026", "Corplol · Sanzo · Plateforme RH", "Python, macOS, React."],
  ["V", "2025", "Credibill", "Suite .NET — WPF, ASP.NET, MAUI. API Laravel."],
  ["V", "2024", "GamerGalaxy · Anderlechtse Gazette", "Laravel, Spring Boot, Python et Pandas."],
  ["—", "—", "Erasmushogeschool Brussel", "Bruxelles. Français, néerlandais, anglais."],
];
