// ============================================================
//  LA SÉANCE — CONTENU
//  Chaque projet est un film : une affiche, un synopsis,
//  une distribution et un générique.
//  👉 Tout se modifie ici.
// ============================================================

const REALISATEUR = {
  nom: "AYOUB OUAADOUD",
  metier: "DÉVELOPPEUR",
  lieu: "Bruxelles, Belgique",
  ecole: "Erasmushogeschool Brussel",
  github: "https://github.com/AyoubO22",
  linkedin: "https://www.linkedin.com/in/ayoub-ouaadoud-5a9550293",
  email: "ayoub.ouaadoud@student.ehb.be",
  note: "Je fais des choses petites, finies, et mises en ligne. Le reste attend son tour.",
};

/* --- affiche : 0 à 3 (composition) · palette : 0 à 5 --- */
const FILMS = [
  {
    id: "gameboxd",
    titre: "GAMEBOXD",
    sousTitre: "Un journal de parties",
    genre: "APPLICATION iOS",
    annee: "2026",
    duree: "52 fichiers",
    affiche: 0, palette: 0,
    synopsis: "Noter, critiquer, garder trace de ce qu'on a joué. Une application native qui traite le jeu vidéo comme on traite les films : avec des archives.",
    distribution: [
      ["Swift 5 · SwiftUI", "rôle principal"],
      ["Architecture MVVM", "structure"],
      ["API RAWG", "documentation"],
      ["WidgetKit", "apparition"],
      ["XCTest · GitHub Actions", "contrôle qualité"],
    ],
    generique: [
      ["ÉCRITURE ET RÉALISATION", "Ayoub Ouaadoud"],
      ["LANGUES", "Français, anglais"],
      ["DÉCORS", "Models · Services · ViewModels · Views"],
      ["SÉCURITÉ", "Clés d'API tenues hors du dépôt"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Gameboxd" }],
  },
  {
    id: "pokedex",
    titre: "COMPÉTITIF",
    sousTitre: "Encyclopédie stratégique",
    genre: "PLATEFORME WEB",
    annee: "2026",
    duree: "61 composants",
    affiche: 1, palette: 1,
    synopsis: "Mille vingt-cinq créatures, neuf cents attaques, et quinze sections de stratégie écrites à la main. Un guide qui ne se contente pas de lister : il explique pourquoi une équipe tient debout.",
    distribution: [
      ["React 18 · TypeScript", "rôle principal"],
      ["Vite · Tailwind · Radix", "mise en scène"],
      ["PokéAPI", "documentation"],
      ["Calculateur de dégâts", "second rôle"],
      ["Constructeur d'équipe", "second rôle"],
    ],
    generique: [
      ["CONTENU STRATÉGIQUE", "Écrit, non généré"],
      ["IMPORT", "Paste Pokémon Showdown"],
      ["QUIZ", "74 questions avec explications"],
      ["ACCESSIBILITÉ", "Thème clair/sombre, taille réglable"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Pokemon-guide" }],
  },
  {
    id: "crm",
    titre: "PASSAGE",
    sousTitre: "Sept systèmes, une voie",
    genre: "SERVICE D'INTÉGRATION",
    annee: "2026",
    duree: "49 schémas",
    affiche: 2, palette: 2,
    synopsis: "Entre une file de messages et un CRM, cinq autres services attendent. Rien ne doit se perdre en route. Un huis clos technique, tourné en équipe.",
    distribution: [
      ["Node.js", "rôle principal"],
      ["RabbitMQ", "premier rôle"],
      ["Salesforce · jsforce", "premier rôle"],
      ["Validation XSD", "contrôle"],
      ["Docker · Compose", "production"],
    ],
    generique: [
      ["PRODUCTION", "Projet d'équipe — IntegrationProject"],
      ["REPRISE", "Files de reprise et file morte"],
      ["JOURNAL", "Winston"],
      ["INTÉGRATION CONTINUE", "À chaque poussée"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/IntegrationProject-Groep1/CRM" }],
  },
  {
    id: "corplol",
    titre: "CORPLOL",
    sousTitre: "Deux camps, à armes égales",
    genre: "APPLICATION DE BUREAU",
    annee: "2026",
    duree: "6 modules",
    affiche: 3, palette: 3,
    synopsis: "Réunir cinq joueurs de force inégale et en faire deux équipes qui s'affrontent sans que le résultat soit joué d'avance. Un vieux problème, résolu par le calcul.",
    distribution: [
      ["Python 3.11", "rôle principal"],
      ["CustomTkinter", "mise en scène"],
      ["API Riot Games", "documentation"],
      ["discord.py", "diffusion"],
    ],
    generique: [
      ["ÉQUILIBRAGE", "Par score et par rôle"],
      ["HISTORIQUE", "Matchs, vainqueurs, séries"],
      ["EXPORT", "Composition formatée pour Discord"],
      ["LICENCE", "MIT — versions publiées"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/corplol" }],
  },
  {
    id: "eylen",
    titre: "EYLEN",
    sousTitre: "Une adresse qu'on peut ouvrir",
    genre: "SITE CLIENT",
    annee: "2026",
    duree: "1 page",
    affiche: 0, palette: 4,
    synopsis: "Un cabinet de médecine esthétique, un vrai commanditaire, un vrai public. Pas de framework, pas d'effets : une page qui se charge et se lit, au téléphone d'abord.",
    distribution: [
      ["HTML · CSS · JavaScript", "rôle principal"],
      ["GitHub Actions", "distribution"],
      ["Contenu patient", "écriture"],
    ],
    generique: [
      ["COMMANDITAIRE", "Cabinet Eylen Kliniek"],
      ["MISE EN LIGNE", "Automatique à chaque poussée"],
      ["ÉTAT", "En ligne"],
    ],
    liens: [
      { label: "VOIR LE SITE", url: "https://zohra-fellah.github.io/Eylen-Kliniek/" },
      { label: "CODE SOURCE", url: "https://github.com/Zohra-Fellah/Eylen-Kliniek" },
    ],
  },
  {
    id: "sanzo",
    titre: "SANZO",
    sousTitre: "Ce qui va avec quoi",
    genre: "APPLICATION macOS",
    annee: "2026",
    duree: "348 palettes",
    affiche: 1, palette: 5,
    synopsis: "Cent cinquante-neuf teintes relevées par un peintre japonais dans les années trente. Elles savaient déjà ce qui s'accorde. L'application se contente de leur poser la question.",
    distribution: [
      ["Swift · SwiftUI", "rôle principal"],
      ["Nuancier Sanzo Wada", "documentation"],
      ["macOS natif", "décor"],
    ],
    generique: [
      ["SÉLECTION", "Pipette, hexadécimal, nuancier"],
      ["SUGGESTIONS", "Haut · bas · veste · accessoire"],
      ["LICENCE", "MIT"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/SanzoOutfitMatcher" }],
  },
  {
    id: "recrutement",
    titre: "CANDIDATURES",
    sousTitre: "Trois regards, un dossier",
    genre: "PLATEFORME WEB",
    annee: "2026",
    duree: "72 composants",
    affiche: 2, palette: 1,
    synopsis: "Celui qui recrute, celui qui décide, et celui qui attend une réponse. Le troisième est trop souvent oublié : ici, il voit où en est son dossier.",
    distribution: [
      ["React · TypeScript", "rôle principal"],
      ["Vite · Tailwind · Radix", "mise en scène"],
      ["Recharts", "tableaux de bord"],
    ],
    generique: [
      ["CADRE", "Generative Application Design"],
      ["ÉVALUATION", "Grille structurée, non libre"],
      ["SOURCE", "Prototype haute-fidélité"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/HR-App" }],
  },
  {
    id: "undercover",
    titre: "UNDERCOVER",
    sousTitre: "Un mot que tous n'ont pas",
    genre: "JEU WEB",
    annee: "2026",
    duree: "3 fichiers",
    affiche: 3, palette: 0,
    synopsis: "Tous reçoivent le même mot. Sauf un, qui en reçoit un autre. Et un dernier, qui n'a rien du tout et devra faire semblant jusqu'au bout.",
    distribution: [
      ["HTML · CSS · JavaScript", "rôle principal"],
      ["localStorage", "mémoire"],
      ["Aucune dépendance", "parti pris"],
    ],
    generique: [
      ["DISPOSITIF", "Un seul téléphone qui circule"],
      ["RÔLES", "Civils, undercover, Mr. White"],
      ["ÉTAT", "En ligne"],
    ],
    liens: [
      { label: "JOUER", url: "https://ayoubo22.github.io/undercover/" },
      { label: "CODE SOURCE", url: "https://github.com/AyoubO22/undercover" },
    ],
  },
  {
    id: "crema",
    titre: "L'INVITATION",
    sousTitre: "Il n'y a pas de seconde soirée",
    genre: "PAGE ÉVÉNEMENT",
    annee: "2026",
    duree: "1 page",
    affiche: 0, palette: 3,
    synopsis: "Une invitation, un formulaire, et l'obligation que ça marche du premier coup. Court métrage : tout se joue sur la fiabilité d'un envoi.",
    distribution: [
      ["HTML · CSS · JavaScript", "rôle principal"],
      ["Google Apps Script", "réception"],
      ["FormSubmit", "doublure"],
    ],
    generique: [
      ["SECOURS", "Bascule courriel si le script ne répond pas"],
      ["DISCRÉTION", "Page non indexée"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/Crema" }],
  },
  {
    id: "seance",
    titre: "LA SÉANCE",
    sousTitre: "Le film que vous regardez",
    genre: "PORTFOLIO",
    annee: "2026",
    duree: "0 image",
    affiche: 2, palette: 4,
    synopsis: "Une filmographie qui n'est pas une filmographie. Les affiches sont composées au code, le grain est calculé, et le générique de fin donne une adresse.",
    distribution: [
      ["HTML · CSS · JavaScript", "rôle principal"],
      ["Affiches génératives", "direction artistique"],
      ["Aucune librairie", "parti pris"],
    ],
    generique: [
      ["AFFICHES", "Composées depuis une graine"],
      ["GRAIN ET SCINTILLEMENT", "Calculés, non filmés"],
      ["VERSIONS", "Ce portfolio existe en quatre mondes"],
    ],
    liens: [{ label: "CODE SOURCE", url: "https://github.com/AyoubO22/undercover/tree/main/portfolio" }],
  },
];

const COMPETENCES = [
  ["JS / TYPESCRIPT", 85], ["REACT / TAILWIND", 80], ["SWIFT / SWIFTUI", 75],
  ["GIT / CI-CD", 75], ["NODE.JS / API", 70], ["PYTHON", 65],
  ["SQL / DONNÉES", 60], ["C# / .NET", 60], ["JAVA / SPRING", 55], ["PHP / LARAVEL", 55],
];

const PARCOURS = [
  ["2026", "Gameboxd", "Application iOS en SwiftUI — MVVM, API RAWG, widget, tests, CI."],
  ["2026", "Service d'intégration CRM", "En équipe : RabbitMQ, Salesforce, XSD, Docker."],
  ["2026", "Encyclopédie compétitive", "React, TypeScript, PokéAPI, calculateur et team builder."],
  ["2026", "Eylen Kliniek", "Site d'un cabinet médical, livré et en ligne."],
  ["2026", "Corplol · Sanzo · Plateforme RH · Undercover", "Python, macOS, React, vanilla."],
  ["2025", "Credibill", "Suite .NET — WPF, ASP.NET, MAUI. API Laravel."],
  ["2024", "GamerGalaxy · Anderlechtse Gazette", "Laravel, Spring Boot, Python et Pandas."],
  ["—", "Erasmushogeschool Brussel", "Bruxelles. Français, néerlandais, anglais."],
];
